#!/usr/bin/env python3
"""Regenerate the per-opcode cases of Mesa's batch shader executor.

riscos-mesa's patches/mesa/mesa-20.3.5-riscos-glsl-batch.patch adds
_mesa_execute_program_batch() to src/mesa/program/prog_execute.c. It runs a
fragment program for up to 32 pixels at a time. Its arithmetic cases are not
written by hand: they are made from the cases of the one-pixel interpreter,
_mesa_execute_program(), in the same file, so the two always compute exactly
the same thing. For each arithmetic opcode this tool:

  - wraps the interpreter's code for it in a loop over the active pixels
    (FOR_LANES ... END_LANES), after "if (!exec) break;";
  - makes two copies of that loop: one using FETCH4F/FETCH1F/STORE4F, the
    branch-free operand access used when di->fast is set, and one using the
    general FETCH4/FETCH1/STORE4;
  - changes the few places that refer to one-pixel state: the address
    register (per pixel: laneAddr[k]), derivatives (machine->CurElement is
    set to the pixel's column) and SWZ's source pointer (lane_src_pointer).

Control-flow opcodes (IF, ELSE, ENDIF, loops, BRK, CONT, KIL, RET, END, CAL,
subroutines, NOP) are written by hand in _mesa_execute_program_batch() and
are left out.

The generated code sits between the lines
    /* BEGIN GENERATED by tools/gen-glsl-batch.py ... */
    /* END GENERATED */
in _mesa_execute_program_batch().

Usage:
    tools/gen-glsl-batch.py prog_execute.c          rewrite the generated part
    tools/gen-glsl-batch.py --check prog_execute.c  exit 1 if it is out of date

To change how an opcode computes its result, edit its case in
_mesa_execute_program(), run this tool, rebuild, and run
tests/host-harness/mesa/run.sh; then regenerate the patch.
"""
import re
import sys

BEGIN = '      /* BEGIN GENERATED by tools/gen-glsl-batch.py from the cases of\n' \
        '       * _mesa_execute_program() above: edit those, then run the tool.\n' \
        '       */\n'
END = '      /* END GENERATED */\n'

# handled by hand in _mesa_execute_program_batch()
CONTROL = {'BGNLOOP', 'ENDLOOP', 'BGNSUB', 'ENDSUB', 'BRK', 'CONT', 'CAL',
           'IF', 'ELSE', 'ENDIF', 'RET', 'END', 'NOP', 'KIL'}


def interpreter_cases(src):
    """The case blocks of the opcode switch in _mesa_execute_program()."""
    start = src.index('_mesa_execute_program(struct gl_context * ctx,')
    sw = src.index('      switch (inst->Opcode) {', start)
    end = src.index('      numExec++;', sw)
    body = src[sw + len('      switch (inst->Opcode) {\n'):end]
    body = body[:body.rindex('      }')]
    parts = re.split(r'(?m)^(?=      (?:case OPCODE_\w+:|default:))', body)
    return [p for p in parts if p.strip()]


def per_lane(inner):
    """Make one opcode's code refer to the current lane's state."""
    inner = inner.replace('machine->AddressReg[0][0] = util_ifloor(t[0]);',
                          'laneAddr[k] = util_ifloor(t[0]);')
    inner = inner.replace('fetch_vector4_deriv(&inst',
                          'machine->CurElement = cols[k];\n'
                          '            fetch_vector4_deriv(&inst')
    inner = inner.replace('get_src_register_pointer(source, machine)',
                          'lane_src_pointer(program, dec, machine, source, '
                          'cols, laneAddr, k)')
    return inner


def generate(src):
    out = []
    for case in interpreter_cases(src):
        m = re.match(r'      case OPCODE_(\w+):', case)
        if not m or m.group(1) in CONTROL:
            continue
        header_end = case.index('\n') + 1
        header, rest = case[:header_end], case[header_end:]
        inner = rest[:rest.rindex('         break;')]
        if 'return' in inner or 'pc =' in inner:
            sys.exit('opcode %s changes control flow: handle it by hand '
                     'and add it to CONTROL' % m.group(1))
        inner = per_lane(inner)
        fast = (inner.replace('FETCH4(', 'FETCH4F(')
                     .replace('FETCH1(', 'FETCH1F(')
                     .replace('STORE4(', 'STORE4F('))
        text = header + '         if (!exec) break;\n'
        if fast != inner:
            text += ('         if (di->fast) {\n'
                     '         FOR_LANES {\n' + fast +
                     '         } END_LANES\n'
                     '         }\n'
                     '         else {\n'
                     '         FOR_LANES {\n' + inner +
                     '         } END_LANES\n'
                     '         }\n')
        else:
            text += ('         FOR_LANES {\n' + inner +
                     '         } END_LANES\n')
        out.append(text + '         break;\n')
    return ''.join(out)


def main():
    args = sys.argv[1:]
    check = args[:1] == ['--check']
    if check:
        args = args[1:]
    if len(args) != 1:
        sys.exit(__doc__)
    path = args[0]
    src = open(path).read()
    try:
        a = src.index(BEGIN) + len(BEGIN)
        b = src.index(END, a)
    except ValueError:
        sys.exit('%s: no BEGIN/END GENERATED markers' % path)
    new = generate(src)
    if check:
        if src[a:b] != new:
            print('%s: the generated batch cases are out of date; run '
                  'tools/gen-glsl-batch.py %s' % (path, path))
            sys.exit(1)
        print('%s: generated batch cases are up to date' % path)
        return
    if src[a:b] != new:
        open(path, 'w').write(src[:a] + new + src[b:])
        print('%s: regenerated' % path)
    else:
        print('%s: already up to date' % path)


if __name__ == '__main__':
    main()
